### PR TITLE
Change button jack keys as they are in sbj (jolla)

### PR DESCRIPTION
**Pull request by kimmoli**
Change KEY_MEDIA to BTN_0 (BTN_MISC)
Change KEY_VOLUMEUP/DOWN to BTN_1 and BTN_2

These are handled on sfos buttonjackd daemon

### CODE REVIEW

**Comment by taaem** [comment]
Whats the exact reason to change it in first place? If KEY_VOLUMEUP/DOWN works why change it and introduce another daemon? 
Is there also a buttonjackd on sbj or some other daemon?

**Comment by kimmoli** [comment]
Also sbj headset buttons are kinda crippled, and buttonjackd could be a solution for it too.
https://together.jolla.com/question/2771/feature-request-support-for-wired-headset-buttonsreleased/

yes, this breaks volume control working oob on onyx, but adds compatibilty between these two devices, in point of view of buttonjackd - which could be used to provide even further functionality for these buttons.

**Comment by taaem** [comment]
So the plan is to make buttonjackd device independend and this would add compatibility with Jolla and eventually other ports?

**Comment by kimmoli** [comment]
Something like that yes

**Comment by taaem** [comment]
Do you know how the keys are on the Jolla C? So we don't break compatibilty with that device?

**Comment by kimmoli** [comment]
hmm (Jolla C)

```
----====( /dev/input/event8 )====----
Name: "msm8909-skue-snd-card Button Jack"
ID: bus 0x0, vendor, 0x0, product 0x0, version 0x0
Type 0x00 (EV_SYN)
Type 0x01 (EV_KEY)
     KEY_VOLUMEDOWN KEY_VOLUMEUP KEY_MEDIA BTN_4 KEY_VOICECOMMAND
```

**Comment by taaem** [comment]
So they are the same as on onyx originally?

**Comment by kimmoli** [comment]
About

**Pull request merged**
